# Form implementation generated from reading ui file 'new_visitor_design.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewVisitor(object):
    def setupUi(self, NewVisitor):
        NewVisitor.setObjectName("NewVisitor")
        NewVisitor.resize(700, 499)
        NewVisitor.setStyleSheet("background-color: rgb(255, 255, 240);")
        self.register_button = QtWidgets.QPushButton(parent=NewVisitor)
        self.register_button.setGeometry(QtCore.QRect(560, 410, 120, 40))
        self.register_button.setStyleSheet("border-radius: 10px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(164, 201, 255);\n"
"font: 12pt \"Arial\";\n"
"")
        self.register_button.setObjectName("register_button")
        self.back_button = QtWidgets.QPushButton(parent=NewVisitor)
        self.back_button.setGeometry(QtCore.QRect(40, 410, 90, 40))
        self.back_button.setStyleSheet("border-radius: 10px;\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(164, 201, 255);\n"
"font: 12pt \"Arial\";\n"
"")
        self.back_button.setObjectName("back_button")
        self.widget = QtWidgets.QWidget(parent=NewVisitor)
        self.widget.setGeometry(QtCore.QRect(190, 70, 321, 248))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setStyleSheet("font: 14pt \"Arial\";\n"
"background-color: white;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("font: 14pt \"Arial\";\n"
"background-color: white;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setStyleSheet("font: 14pt \"Arial\";\n"
"background-color: white;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.secondName = QtWidgets.QLineEdit(parent=self.widget)
        self.secondName.setStyleSheet("border-radius: 10px;\n"
"font: 12pt \"Arial\";\n"
"border: 2px solid rgb(164, 201, 255);\n"
"background-color: white;\n"
"")
        self.secondName.setObjectName("secondName")
        self.verticalLayout.addWidget(self.secondName)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.firstName = QtWidgets.QLineEdit(parent=self.widget)
        self.firstName.setStyleSheet("border-radius: 10px;\n"
"font: 12pt \"Arial\";\n"
"border: 2px solid rgb(164, 201, 255);\n"
"background-color: white;\n"
"")
        self.firstName.setObjectName("firstName")
        self.verticalLayout.addWidget(self.firstName)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.dateEdit = QtWidgets.QDateEdit(parent=self.widget)
        self.dateEdit.setStyleSheet("border-radius: 10px;\n"
"font: 12pt \"Arial\";\n"
"border: 2px solid rgb(164, 201, 255);\n"
"background-color: white;\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout.addWidget(self.dateEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(NewVisitor)
        QtCore.QMetaObject.connectSlotsByName(NewVisitor)

    def retranslateUi(self, NewVisitor):
        _translate = QtCore.QCoreApplication.translate
        NewVisitor.setWindowTitle(_translate("NewVisitor", "Form"))
        self.register_button.setText(_translate("NewVisitor", "Зареєструвати"))
        self.back_button.setText(_translate("NewVisitor", "Назад"))
        self.label.setText(_translate("NewVisitor", "Прізвище:"))
        self.label_3.setText(_translate("NewVisitor", "Ім\'я:"))
        self.label_4.setText(_translate("NewVisitor", "Дата реєстрації:"))
